main = "./src/index.ts"
compatibility_date = "2022-10-08"
workers_dev = true

# Median CPU time is ~2ms so safely within the 50ms bundled worker limit
usage_model = "bundled"

# Staging
# name = "s3-to-r2-staging"
# Comment out in development, doesn't seem to work with it
# route = { pattern = "r2-staging.robinpro.gallery", custom_domain = true, zone_id = "fcdcfddc23b623c76eb092dcd7896964" }

# Production
name = "s3-to-r2"

[vars]
# Staging
# AWS_HOSTNAME = "awesome-gallery-staging.s3.us-west-2.amazonaws.com"
# Production
AWS_HOSTNAME = "awesome-gallery.s3.us-west-2.amazonaws.com"

[[r2_buckets]]
binding = "R2"
preview_bucket_name = "images-preview"
# Staging
# bucket_name = "images-staging"
# Production
bucket_name = "images"
